<a href="https://colab.research.google.com/github/deepakri201/convertToDICOM/blob/main/TotalSegmentator_DICOM_to_nifti_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is a WIP for converting the TotalSegmentator nifti CT and nifti label file to DICOM and DICOM Segmentation respectively.



Deepa Krishnaswamy

Brigham and Women's Hospital

Sept 21 2023

# Environment setup

In [1]:
import os
import sys
import time
import json
import subprocess
import glob
import shutil
import numpy as np

In [13]:
# SimpleITK
!pip install simpleITK
import SimpleITK as sitk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 MB 9.6 MB/s eta 0:00:00


## Instal dcmqi for converting nifti to DICOM Segmentation object

In [3]:
# DCMQI - to convert nifti to DICOM Segmentation object
!wget https://github.com/QIICR/dcmqi/releases/download/v1.2.5/dcmqi-1.2.5-linux.tar.gz
!tar zxvf dcmqi-1.2.5-linux.tar.gz
!cp dcmqi-1.2.5-linux/bin/* /usr/local/bin/

--2023-09-21 19:40:04--  https://github.com/QIICR/dcmqi/releases/download/v1.2.5/dcmqi-1.2.5-linux.tar.gz
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/50675718/79d3ad95-9f0c-42a4-a1c5-bf5a63461894?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230921%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230921T194004Z&X-Amz-Expires=300&X-Amz-Signature=64566d889dae419a0448f7f1c226ef92305242792722a05f49a93942af311a46&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=50675718&response-content-disposition=attachment%3B%20filename%3Ddcmqi-1.2.5-linux.tar.gz&response-content-type=application%2Foctet-stream [following]
--2023-09-21 19:40:04--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/50675718/79d3ad95-9f0c-42a4-a1c5-bf5a634

## Install necessary packages for converting DICOM to nifti for pixelmed

In [4]:
!apt install openjdk-8-jdk-headless

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libxtst6 openjdk-8-jre-headless
Suggested packages:
  openjdk-8-demo openjdk-8-source libnss-mdns fonts-dejavu-extra fonts-nanum
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  libxtst6 openjdk-8-jdk-headless openjdk-8-jre-headless
0 upgraded, 3 newly installed, 0 to remove and 18 not upgraded.
Need to get 39.7 MB of archives.
After this operation, 144 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-8-jre-headless amd64 8u382-ga-1~22.04.1 [30.8 MB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-8-jdk-headless amd64 8u382-ga-1~22.04.1 [8,851 kB]
Fetched

In [5]:
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

In [6]:
!wget http://www.dclunie.com/pixelmed/software/20221004_current/pixelmedjavadicom_binaryrelease.20221004.tar.bz2
!wget http://www.dclunie.com/pixelmed/software/20221004_current/pixelmedjavadicom_dependencyrelease.20221004.tar.bz2

!bunzip2  '/content/pixelmedjavadicom_binaryrelease.20221004.tar.bz2'
!bunzip2 '/content/pixelmedjavadicom_dependencyrelease.20221004.tar.bz2'

--2023-09-21 19:40:39--  http://www.dclunie.com/pixelmed/software/20221004_current/pixelmedjavadicom_binaryrelease.20221004.tar.bz2
Resolving www.dclunie.com (www.dclunie.com)... 52.84.162.81, 52.84.162.67, 52.84.162.98, ...
Connecting to www.dclunie.com (www.dclunie.com)|52.84.162.81|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3407406 (3.2M) [application/x-bzip2]
Saving to: ‘pixelmedjavadicom_binaryrelease.20221004.tar.bz2’

pixelmedjavadicom_b 100%[===================>]   3.25M  7.03MB/s    in 0.5s    

2023-09-21 19:40:40 (7.03 MB/s) - ‘pixelmedjavadicom_binaryrelease.20221004.tar.bz2’ saved [3407406/3407406]

--2023-09-21 19:40:40--  http://www.dclunie.com/pixelmed/software/20221004_current/pixelmedjavadicom_dependencyrelease.20221004.tar.bz2
Resolving www.dclunie.com (www.dclunie.com)... 52.84.162.81, 52.84.162.67, 52.84.162.98, ...
Connecting to www.dclunie.com (www.dclunie.com)|52.84.162.81|:80... connected.
HTTP request sent, awaiting response... 20

In [7]:
if not os.path.isdir('/content/binaries'):
  os.mkdir('/content/binaries')
if not os.path.isdir('/content/dependencies'):
  os.mkdir('/content/dependencies')
!tar -xvf '/content/pixelmedjavadicom_binaryrelease.20221004.tar' -C '/content/binaries'
!tar -xvf '/content/pixelmedjavadicom_dependencyrelease.20221004.tar' -C '/content/dependencies'


pixelmed.jar
BUILDDATE
COPYRIGHT
DeidentifyAndRedact.bat
DeidentifyAndRedact.sh
DeidentifyAndRedactWithOriginalFileName.bat
DicomAttributeBrowser.sh
DicomBrowser.sh
DicomCleanerAssumingJREInstalled.bat
DicomCleanerWithOwnJRE.bat
DicomImageViewer.bat
DicomImageViewer.sh
DicomImageViewerWithCDJRE.bat
DicomImageViewerWithOwnJRE.bat
DicomInstanceValidator.sh
DicomSRValidator.sh
DoseUtilityAssumingJREInstalled.bat
DoseUtilityWithOwnJRE.bat
ECGViewer.bat
ECGViewer.sh
MoveDicomFilesIntoHierarchy.sh
NetworkMediaImporter.bat
NetworkMediaImporter.sh
StructuredReportBrowser.sh
StudyReceiver.bat
studyreceiver.properties
Makefile
Makefile.common.mk
README
sample.com.pixelmed.display.DicomImageViewer.properties
lib/additional/pixelmed_codec.jar
lib/additional/pixelmed_imageio.jar
./lib/additional/commons-codec-1.3.jar
lib/additional/commons-net-ftp-2.0.jar
./lib/additional/commons-compress-1.12.jar
lib/additional/hsqldb.jar
lib/additional/vecmath1.2-1.14.jar
lib/additional/jmdns.jar
lib/additional/a

In [8]:
!tar -xvf '/content/pixelmedjavadicom_binaryrelease.20221004.tar' -C '/content/binaries'


pixelmed.jar
BUILDDATE
COPYRIGHT
DeidentifyAndRedact.bat
DeidentifyAndRedact.sh
DeidentifyAndRedactWithOriginalFileName.bat
DicomAttributeBrowser.sh
DicomBrowser.sh
DicomCleanerAssumingJREInstalled.bat
DicomCleanerWithOwnJRE.bat
DicomImageViewer.bat
DicomImageViewer.sh
DicomImageViewerWithCDJRE.bat
DicomImageViewerWithOwnJRE.bat
DicomInstanceValidator.sh
DicomSRValidator.sh
DoseUtilityAssumingJREInstalled.bat
DoseUtilityWithOwnJRE.bat
ECGViewer.bat
ECGViewer.sh
MoveDicomFilesIntoHierarchy.sh
NetworkMediaImporter.bat
NetworkMediaImporter.sh
StructuredReportBrowser.sh
StudyReceiver.bat
studyreceiver.properties
Makefile
Makefile.common.mk
README
sample.com.pixelmed.display.DicomImageViewer.properties


Copy the dependencies

In [9]:
if not os.path.isdir('/content/binaries/lib'):
  os.mkdir('/content/binaries/lib')
!cp -r /content/dependencies/lib/* /content/binaries/lib

Test command to make sure it works

In [10]:
%cd /content/binaries/
!pwd
!java -Xmx512m -Xms512m -cp "./pixelmed.jar:./lib/additional/hsqldb.jar:./lib/additional/excalibur-bzip2-1.0.jar:./lib/additional/vecmath1.2-1.14.jar:./lib/additional/jmdns.jar:./lib/additional/commons-codec-1.3.jar:./lib/additional/jai_imageio.jar" com.pixelmed.dicom.MultiFrameImageFactory

/content/binaries
/content/binaries
Error: Incorrect number of arguments
Usage: MultiFrameImageFactory inputPaths outputPath


In [11]:
!java -cp "/content/binaries/pixelmed.jar" -Djava.awt.headless=true com.pixelmed.convert.NIfTI1ToDicom "/content/totalsegmentator_ct_fixed/s0004/ct.nii.gz" "/content/ct.dcm" "s0004" "s0004" "1" "1" "1"


[main] ERROR com.pixelmed.convert.NIfTI1ToDicom java.io.FileNotFoundException: /content/totalsegmentator_ct_fixed/s0004/ct.nii.gz (No such file or directory)
java.io.FileNotFoundException: /content/totalsegmentator_ct_fixed/s0004/ct.nii.gz (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.pixelmed.dicom.BinaryInputStream.<init>(BinaryInputStream.java:50)
	at com.pixelmed.convert.NIfTI1Header.<init>(NIfTI1Header.java:305)
	at com.pixelmed.convert.NIfTI1ToDicom.<init>(NIfTI1ToDicom.java:519)
	at com.pixelmed.convert.NIfTI1ToDicom.main(NIfTI1ToDicom.java:563)


## Install dcmtk for printing contents of DICOM files

Install dcmtk in order to use dcmdump

In [24]:
!wget https://dicom.offis.de/download/dcmtk/dcmtk367/bin/dcmtk-3.6.7-linux-debian-11-x86_64-static.tar.bz2 .

--2023-09-21 20:02:38--  https://dicom.offis.de/download/dcmtk/dcmtk367/bin/dcmtk-3.6.7-linux-debian-11-x86_64-static.tar.bz2
Resolving dicom.offis.de (dicom.offis.de)... 134.106.52.157
Connecting to dicom.offis.de (dicom.offis.de)|134.106.52.157|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 723511218 (690M) [application/x-bzip2]
Saving to: ‘dcmtk-3.6.7-linux-debian-11-x86_64-static.tar.bz2’

dcmtk-3.6.7-linux-d 100%[===================>] 689.99M  16.3MB/s    in 43s     

2023-09-21 20:03:22 (16.0 MB/s) - ‘dcmtk-3.6.7-linux-debian-11-x86_64-static.tar.bz2’ saved [723511218/723511218]

--2023-09-21 20:03:22--  http://./
Resolving . (.)... failed: No address associated with hostname.
wget: unable to resolve host address ‘.’
FINISHED --2023-09-21 20:03:22--
Total wall clock time: 44s
Downloaded: 1 files, 690M in 43s (16.0 MB/s)


In [25]:
!bunzip2  'dcmtk-3.6.7-linux-debian-11-x86_64-static.tar.bz2'

In [26]:
if not os.path.isdir('/content/dcmtk'):
  os.mkdir('/content/dcmtk')
!tar -xvf 'dcmtk-3.6.7-linux-debian-11-x86_64-static.tar' -C '/content/dcmtk'

dcmtk-3.6.7-linux-x86_64-static/bin/
dcmtk-3.6.7-linux-x86_64-static/bin/xml2dcm
dcmtk-3.6.7-linux-x86_64-static/bin/dcmmklut
dcmtk-3.6.7-linux-x86_64-static/bin/dcmcjpeg
dcmtk-3.6.7-linux-x86_64-static/bin/dcmp2pgm
dcmtk-3.6.7-linux-x86_64-static/bin/dcm2pdf
dcmtk-3.6.7-linux-x86_64-static/bin/dcmpschk
dcmtk-3.6.7-linux-x86_64-static/bin/dcmsign
dcmtk-3.6.7-linux-x86_64-static/bin/dcmdrle
dcmtk-3.6.7-linux-x86_64-static/bin/mkreport
dcmtk-3.6.7-linux-x86_64-static/bin/dcmgpdir
dcmtk-3.6.7-linux-x86_64-static/bin/echoscu
dcmtk-3.6.7-linux-x86_64-static/bin/dcmcjpls
dcmtk-3.6.7-linux-x86_64-static/bin/dcmsend
dcmtk-3.6.7-linux-x86_64-static/bin/movescu
dcmtk-3.6.7-linux-x86_64-static/bin/dcod2lum
dcmtk-3.6.7-linux-x86_64-static/bin/dcmmkdir
dcmtk-3.6.7-linux-x86_64-static/bin/dcmpsprt
dcmtk-3.6.7-linux-x86_64-static/bin/dcmqrscp
dcmtk-3.6.7-linux-x86_64-static/bin/dcmpssnd
dcmtk-3.6.7-linux-x86_64-static/bin/wlmscpfs
dcmtk-3.6.7-linux-x86_64-static/bin/dsr2html
dcmtk-3.6.7-linux-x86_64-

# Get TotalSegmentator data from github

I have already uploaded a sample CT file and the corresponding label file to github. The label file was created using Jakob's function `combine_masks_to_multilabel_file`.

In [2]:
!wget -O /content/s0011_ct.nii.gz https://raw.githubusercontent.com/deepakri201/convertToDICOM/main/sample_data/s0011_ct.nii.gz
!wget -O /content/s0011_seg.nii.gz https://raw.githubusercontent.com/deepakri201/convertToDICOM/main/sample_data/s0011_seg.nii.gz

--2023-09-21 19:36:32--  https://raw.githubusercontent.com/deepakri201/convertToDICOM/main/sample_data/s0011_ct.nii.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58738830 (56M) [application/octet-stream]
Saving to: ‘/content/s011_ct.nii.gz’

/content/s011_ct.ni 100%[===================>]  56.02M   272MB/s    in 0.2s    

2023-09-21 19:36:34 (272 MB/s) - ‘/content/s011_ct.nii.gz’ saved [58738830/58738830]

--2023-09-21 19:36:34--  https://raw.githubusercontent.com/deepakri201/convertToDICOM/main/sample_data/s0011_seg.nii.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP requ

# Did not work - Convert the CT nii file to DICOM using pixelmed - NIfTI1ToDicom

Did not work when converting nifti to DICOM, I get the following error:


```
[main] ERROR com.pixelmed.convert.NIfTI1ToDicom com.pixelmed.convert.NIfTI1Exception: Not a NIfTI-1 magic number
com.pixelmed.convert.NIfTI1Exception: Not a NIfTI-1 magic number
	at com.pixelmed.convert.NIfTI1Header.<init>(NIfTI1Header.java:438)
	at com.pixelmed.convert.NIfTI1ToDicom.<init>(NIfTI1ToDicom.java:519)
	at com.pixelmed.convert.NIfTI1ToDicom.main(NIfTI1ToDicom.java:563)
```

In [12]:
!java -cp "/content/binaries/pixelmed.jar" -Djava.awt.headless=true com.pixelmed.convert.NIfTI1ToDicom "/content/s0011_ct.nii.gz" "/content/s0011_ct_from_nii.dcm" "s0011" "s0011" "1" "1" "1"


[main] ERROR com.pixelmed.convert.NIfTI1ToDicom com.pixelmed.convert.NIfTI1Exception: Not a NIfTI-1 magic number
com.pixelmed.convert.NIfTI1Exception: Not a NIfTI-1 magic number
	at com.pixelmed.convert.NIfTI1Header.<init>(NIfTI1Header.java:438)
	at com.pixelmed.convert.NIfTI1ToDicom.<init>(NIfTI1ToDicom.java:519)
	at com.pixelmed.convert.NIfTI1ToDicom.main(NIfTI1ToDicom.java:563)


# Did not work - Convert the CT nii file to nrrd, and then to DICOM using pixelmed - NRRDToDicom

Error in conversion - conversion of Int32 not supported:

```
[main] ERROR com.pixelmed.convert.NRRDToDicom com.pixelmed.dicom.DicomException: Conversion of INT32 not supported
com.pixelmed.dicom.DicomException: Conversion of INT32 not supported
	at com.pixelmed.convert.NRRDToDicom.generateDICOMPixelDataModuleAttributesFromNRRDFile(NRRDToDicom.java:386)
	at com.pixelmed.convert.NRRDToDicom.<init>(NRRDToDicom.java:649)
	at com.pixelmed.convert.NRRDToDicom.main(NRRDToDicom.java:690)
```

In [14]:
# Try converting nifti to nrrd and see if I can use the NRRDToDICOM command

reader = sitk.ImageFileReader()
reader.SetImageIO("NiftiImageIO")
reader.SetFileName("/content/s0011_ct.nii.gz")
image = reader.Execute()

writer = sitk.ImageFileWriter()
writer.SetFileName('/content/s0011_ct.nrrd')
writer.Execute(image)


In [15]:
!java -cp "/content/binaries/pixelmed.jar" -Djava.awt.headless=true com.pixelmed.convert.NRRDToDicom "/content/s0011_ct.nrrd" "/content/s0011_ct_from_nrrd.dcm" "s0011" "s0011" "1" "1" "1"


[main] INFO com.pixelmed.convert.NRRDHeader Comment: "# Complete NRRD file format specification at:"
[main] INFO com.pixelmed.convert.NRRDHeader Comment: "# http://teem.sourceforge.net/nrrd/format.html"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "type" Description: "int"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "dimension" Description: "3"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "space" Description: "left-posterior-superior"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "sizes" Description: "311 311 431"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "space directions" Description: "(-1.5,0,0) (0,-1.5,0) (0,0,1.5)"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "kinds" Description: "domain domain domain"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "endian" Description: "little"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "encoding" Description: "raw"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "space origin" Description: "(

# Convert the CT nii file to int16, then to nrrd, and then to DICOM using pixelmed - NRRDToDicom

Did not produce an error in the conversion of NRRD to DICOM, however when validating the DICOM file I got the error:

```
# IOD (SOP Class) unrecognized
```



In [19]:
# Try converting nifti to nrrd and see if I can use the NRRDToDICOM command

reader = sitk.ImageFileReader()
reader.SetImageIO("NiftiImageIO")
reader.SetFileName("/content/s0011_ct.nii.gz")
image = reader.Execute()

arr64 = sitk.Cast(image, sitk.sitkInt16)

writer = sitk.ImageFileWriter()
writer.SetFileName('/content/s0011_ct.nrrd')
writer.Execute(arr64)


In [20]:
!java -cp "/content/binaries/pixelmed.jar" -Djava.awt.headless=true com.pixelmed.convert.NRRDToDicom "/content/s0011_ct.nrrd" "/content/s0011_ct_from_nrrd.dcm" "s0011" "s0011" "1" "1" "1"


[main] INFO com.pixelmed.convert.NRRDHeader Comment: "# Complete NRRD file format specification at:"
[main] INFO com.pixelmed.convert.NRRDHeader Comment: "# http://teem.sourceforge.net/nrrd/format.html"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "type" Description: "short"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "dimension" Description: "3"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "space" Description: "left-posterior-superior"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "sizes" Description: "311 311 431"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "space directions" Description: "(-1.5,0,0) (0,-1.5,0) (0,0,1.5)"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "kinds" Description: "domain domain domain"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "endian" Description: "little"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "encoding" Description: "raw"
[main] INFO com.pixelmed.convert.NRRDHeader Field: "space origin" Description: 

In [22]:
# validate the DICOM file

!bash DicomInstanceValidator.sh '/content/s0011_ct_from_nrrd.dcm'

IOD (SOP Class) unrecognized


In [27]:
# Print contents of file

!/content/dcmtk/dcmtk-3.6.7-linux-x86_64-static/bin/dcmdump /content/dcm/s0011_ct_from_nrrd.dcm

Streaming output truncated to the last 5000 lines.
      (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
    (fffe,e0dd) na (SequenceDelimitationItem)               #   0, 0 SequenceDelimitationItem
    (0020,9113) SQ (Sequence with undefined length #=1)     # u/l, 1 Unknown Tag & Data
      (fffe,e000) na (Item with undefined length #=1)         # u/l, 1 Item
        (0020,0032) DS [236.544921875\45.544921875\168.5]       #  32, 3 Unknown Tag & Data
      (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
    (fffe,e0dd) na (SequenceDelimitationItem)               #   0, 0 SequenceDelimitationItem
    (0020,9171) SQ (Sequence with undefined length #=1)     # u/l, 1 Unknown Tag & Data
      (fffe,e000) na (Item with undefined length #=0)         # u/l, 1 Item
      (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
    (fffe,e0dd) na (SequenceDelimitationItem)               #   0

# Did not work - Convert the label nii file to a DICOM Segmentation object

I got the following error when converting to DICOM SEG:


```
dcmqi repository URL: git@github.com:QIICR/dcmqi.git revision: 1153738 tag: v1.2.5
Loaded segmentation from /content/s0011_seg.nii.gz
Searching recursively /content/dcm for DICOM files
Condition failed: Tag not found in ../../include/dcmqi/ConverterBase.h:296
Fatal error encountered.
```

Let's try seeing if a SEG object can be created.

In [23]:
!mkdir '/content/dcm'
!cp '/content/s0011_ct_from_nrrd.dcm' '/content/dcm'

mkdir: cannot create directory ‘/content/dcm’: File exists


Get the metadata json file already created

In [28]:
!wget -O /content/metadata.json https://raw.githubusercontent.com/ImagingDataCommons/Cloud-Resources-Workflows/main/configs/TotalSegmentator/dicomseg_metadata_whole_slicerAsRef.json

--2023-09-21 20:07:47--  https://raw.githubusercontent.com/ImagingDataCommons/Cloud-Resources-Workflows/main/configs/TotalSegmentator/dicomseg_metadata_whole_slicerAsRef.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 99233 (97K) [text/plain]
Saving to: ‘/content/metadata.json’

/content/metadata.j 100%[===================>]  96.91K  --.-KB/s    in 0.02s   

2023-09-21 20:07:47 (5.94 MB/s) - ‘/content/metadata.json’ saved [99233/99233]



In [29]:
inputImageList = '/content/s0011_seg.nii.gz'
inputDICOMDirectory = '/content/dcm'
outputDICOM = '/content/s0011_seg.dcm'
inputMetadata = '/content/metadata.json'

!itkimage2segimage --inputImageList $inputImageList --inputDICOMDirectory $inputDICOMDirectory --outputDICOM $outputDICOM --inputMetadata $inputMetadata

# !itkimage2segimage --inputImageList {inference_nifti_filename} --inputDICOMDirectory {curr_dir}/idc_data/ --outputDICOM {curr_dir}/itkimage2segimage/{series_id}/{series_id}.dcm --inputMetadata {curr_dir}/dicomseg_metadata_whole_slicerAsRef.json --skip >> /dev/null


dcmqi repository URL: git@github.com:QIICR/dcmqi.git revision: 1153738 tag: v1.2.5
Loaded segmentation from /content/s0011_seg.nii.gz
Searching recursively /content/dcm for DICOM files
Condition failed: Tag not found in ../../include/dcmqi/ConverterBase.h:296
Fatal error encountered.


# Alternate ideas

I used Slicer to create the DICOM files from the CT nifti file. This was run locally.

In [ ]:
### Download the ct nii file ###
### Run in Slicer python console ###

# # import nifti file as node
# volumeNode = slicer.util.loadVolume("C:/Users/deepa/Downloads/s0011_ct.nii.gz")
# # volumeNode = getNode("CTChest")

# outputFolder = "c:/Users/deepa/Downloads/dicom-output"

# # Create patient and study and put the volume under the study
# shNode = slicer.vtkMRMLSubjectHierarchyNode.GetSubjectHierarchyNode(slicer.mrmlScene)
# # set IDs. Note: these IDs are not specifying DICOM tags, but only the names that appear in the hierarchy tree
# patientItemID = shNode.CreateSubjectItem(shNode.GetSceneItemID(), "test patient")
# studyItemID = shNode.CreateStudyItem(patientItemID, "test study")
# volumeShItemID = shNode.GetItemByDataNode(volumeNode)
# shNode.SetItemParent(volumeShItemID, studyItemID)

# import DICOMScalarVolumePlugin
# exporter = DICOMScalarVolumePlugin.DICOMScalarVolumePluginClass()
# exportables = exporter.examineForExport(volumeShItemID)
# for exp in exportables:
#   # set output folder
#   exp.directory = outputFolder
#   # here we set DICOM PatientID and StudyID tags
#   exp.setTag('PatientID', "test patient")
#   exp.setTag('StudyID', "test study")

# exporter.export(exportables)


I then uploaded these CT DICOM files manually to Colab, and then ran itkimage2segimage to convert to DICOM SEG. Of course I could have also done this using the DICOMSegmentationPlugin in Slicer.



In [30]:
inputImageList = '/content/s0011_seg.nii.gz'
inputDICOMDirectory = '/content/slicer_dcm_s0011'
outputDICOM = '/content/s0011_seg.dcm'
inputMetadata = '/content/metadata.json'

!itkimage2segimage --inputImageList $inputImageList --inputDICOMDirectory $inputDICOMDirectory --outputDICOM $outputDICOM --inputMetadata $inputMetadata --skip


Streaming output truncated to the last 5000 lines.
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source image item
Added source 